# Generated by Django 5.1.7 on 2025-03-16 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione_clienti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='freelance',
            field=models.ForeignKey(limit_choices_to={'ruolo': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='clienti_gestiti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profilo_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progetto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progetti', to='gestione_clienti.cliente'),
        ),
    ]
