# Generated by Django 5.1.7 on 2025-03-25 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_clienti', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progetto',
            name='avanzamento_percentuale',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progetto',
            name='freelance',
            field=models.ForeignKey(default=2, limit_choices_to={'ruolo': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='progetti_gestiti', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progetto',
            name='ore_lavorate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
