# Generated by Django 5.1.7 on 2025-03-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_utenti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ruolo',
            field=models.CharField(choices=[('F', 'Freelance'), ('A', 'Admin'), ('C', 'Cliente')], default='F', max_length=1, verbose_name='Ruolo Utente'),
        ),
    ]
