# Generated by Django 5.1.7 on 2025-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_utenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_freelance_pro',
            field=models.BooleanField(default=False, verbose_name='Freelance Pro (accesso backend)'),
        ),
    ]
