# Generated by Django 5.1.7 on 2025-03-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione_clienti', '0001_initial'),
        ('gestione_utenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField()),
                ('stato', models.CharField(choices=[('A', 'Aperto'), ('I', 'In Lavorazione'), ('R', 'Risolto')], default='A', max_length=1)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('ultima_modifica', models.DateTimeField(auto_now=True)),
                ('assegnato_a', models.ForeignKey(blank=True, limit_choices_to={'ruolo': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assegnati', to='gestione_utenti.user')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='gestione_clienti.cliente')),
                ('progetto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='gestione_clienti.progetto')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='CommentoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_utenti.user')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='gestione_ticket.ticket')),
            ],
            options={
                'verbose_name': 'Commento Ticket',
                'verbose_name_plural': 'Commenti Ticket',
            },
        ),
    ]
