# Generated by Django 5.1.7 on 2025-03-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Commento Ticket',
                'verbose_name_plural': 'Commenti Ticket',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField()),
                ('stato', models.CharField(choices=[('A', 'Aperto'), ('I', 'In Lavorazione'), ('R', 'Risolto')], default='A', max_length=1)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('ultima_modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Ticket',
            },
        ),
    ]
