# Generated by Django 5.1.7 on 2025-03-16 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione_clienti', '0002_initial'),
        ('gestione_ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentoticket',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assegnato_a',
            field=models.ForeignKey(blank=True, limit_choices_to={'ruolo': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assegnati', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='gestione_clienti.cliente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='progetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='gestione_clienti.progetto'),
        ),
        migrations.AddField(
            model_name='commentoticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='gestione_ticket.ticket'),
        ),
    ]
