# Generated by Django 5.1.7 on 2025-03-16 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione_fatture', '0001_initial'),
        ('gestione_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fattura',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fatture', to='gestione_ticket.ticket'),
        ),
    ]
