# Generated by Django 5.1.7 on 2025-03-16 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione_clienti', '0002_initial'),
        ('gestione_log', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attivitalog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportprogetto',
            name='progetto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='gestione_clienti.progetto'),
        ),
    ]
